EnterpriseProject/Models/Idea.cs
using System;
using System.Collections;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace EnterpriseProject.Models
{
    public class Idea 
    {
        [Key]
        public int Id { get; set; }

        public string Text { get; set; }
        public int FileId { get; set; }
        public DateTime DateTime { get; set; }

        [Required]
        public string UserId { get; set; }
        [ForeignKey("UserId")]
        public ApplicationUser ApplicationUser { get; set; }
        
        [Required]
        public int CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        public Category Category { get; set; }
        
        [Required]
        public int TopicId { get; set; }
        [ForeignKey("TopicId")]
        public Topic Topic { get; set; }
        
    }
}

EnterpriseProject/Areas/Authenticated/Controllers/IdeasController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EnterpriseProject.Data;
using EnterpriseProject.Models;
using EnterpriseProject.Utility;
using EnterpriseProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using File = EnterpriseProject.Models.File;

namespace EnterpriseProject.Areas.Authenticated.Controllers
{
    [Area(SD.Authenticated)]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Manager + "," + SD.Role_Staff + "," + SD.Role_Coordinator)]
    public class IdeasController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ISendMailService _emailSender;

        public IdeasController(ApplicationDbContext db,UserManager<IdentityUser> userManager, ISendMailService emailSender)
        {
            _db = db;
            _userManager = userManager;
            _emailSender = emailSender;
        }
        // GET
        public IActionResult Index(string searchString, int topicId)
        {
            ViewData["Message"] = TempData["Message"];
            var listIdea = _db.Ideas.Where(_=>_.TopicId == topicId).Include(i => i.ApplicationUser)
                .Include(i => i.Category)
                .Include(i => i.Topic).ToList();
            
            var reacts = new List<ReactVM>();
            
            if (!String.IsNullOrEmpty(searchString))
            {
                listIdea = listIdea.Where(s => s.Text.Contains(searchString)).ToList();
            }
            
            foreach (var idea in listIdea)
            {
                var like = _db.Reacts.Where(_ => _.IdeaId == idea.Id).Sum(_ => _.Like);
                var disLike = _db.Reacts.Where(_ => _.IdeaId == idea.Id).Sum(_ => _.DisLike);
                var view = _db.Views.Count(_ => _.IdeaId == idea.Id);
                var fileName = _db.Files.FirstOrDefault(_ => _.Id == idea.FileId).Name;
                var react = new ReactVM()
                {
                    View = view,
                    Idea = idea,
                    Like = like,
                    DisLike = disLike,
                    FileName = fileName
                };
                
                reacts.Add(react);
            }

            var response = new TopicsVM()
            {
                ReactVms = reacts,
                Topic = _db.Topics.Find(topicId)
            };
            
            return View(response);
        }

        [HttpGet]
        public IActionResult Upsert(int? id, int topicId )
        {
            
            IdeaVM ideaVm = new IdeaVM()
            {
                CategoryList = categoriesSelectListItems(),
                TopicId = topicId
            };
            
            if (id == null)
            {
                return View(ideaVm);
            }

            var idea = _db.Ideas.Find(id);
            ideaVm.Id = idea.Id;
            ideaVm.Text = idea.Text;
            ideaVm.DateTime = idea.DateTime;
            ideaVm.CategoryId = idea.CategoryId;
            ideaVm.TopicId = idea.TopicId;
            ideaVm.FileName = _db.Files.Find(idea.FileId).Name;
            return View(ideaVm);
        }
        
        
        [HttpPost]
        public async Task<IActionResult> UpSert(IdeaVM ideaVm)
        {
            if (ModelState.IsValid)
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                
                if (ideaVm.IsAgree)
                {
                    if (ideaVm.Id == 0)
                    {
                        // SendEmail to QA coordinator
                        var currentUser = _db.ApplicationUsers.FirstOrDefault(i => i.Id == claims.Value);
                        var userList = _db.ApplicationUsers.Where(_ => _.DepartmentId == currentUser.DepartmentId).ToList();
                        ApplicationUser qaCoordinator = new ApplicationUser();
                        foreach (var user in userList)
                        {
                            var roleTemp = await _userManager.GetRolesAsync(user);
                            if (roleTemp.First() == SD.Role_Coordinator)
                            {
                                qaCoordinator = user;
                                break;
                            }
                        }
                        
                        // add file
                        if (ideaVm.File == null || ideaVm.File.Length == 0)
                            return BadRequest("No file selected");

                        var fileModel = new File
                        {
                            Name = ideaVm.File.FileName,
                            ContentType = ideaVm.File.ContentType
                        };

                        using (var memoryStream = new MemoryStream())
                        {
                            await ideaVm.File.CopyToAsync(memoryStream);
                            fileModel.Data = memoryStream.ToArray();
                        }
                        _db.Files.Add(fileModel);
                        _db.SaveChanges();
                        
                        // create idea
                        var ideaCreate = new Idea()
                        {
                            Text = ideaVm.Text,
                            DateTime = ideaVm.DateTime,
                            FileId = fileModel.Id,
                            CategoryId = ideaVm.CategoryId,
                            TopicId = ideaVm.TopicId,
                            UserId = claims.Value
                        };
                        _db.Ideas.Add(ideaCreate);
                        _db.SaveChanges();

                        // Check idea is successful or not and send mail to coordinator
                        if (qaCoordinator != null && qaCoordinator.Email != null)
                        {
                            await _emailSender.SendEmailAsync(qaCoordinator.Email, "New Idea Is Added",
                                $"<div style='color: black;'><h1 style='color: black;'>New Idea Is Added</h1><p style='color: black;'><strong>From:</strong> {_db.ApplicationUsers.Find(claims.Value).FullName} ({_db.ApplicationUsers.Find(claims.Value).Email})</p><p style='color: black;'><strong>The new idea's name is added by:</strong> {_db.Ideas.Find(ideaCreate.Id).Text}</p><p style='color: black;'><strong>ideas added in topics:</strong> {_db.Topics.Find(ideaVm.TopicId).Name}</p><p style='color: black;'><strong>Time for posting ideas:</strong> {_db.Ideas.Find(ideaCreate.Id).DateTime}</p><p style='color: black;'><strong>Best Regards!</strong></p></div>");
                        }
                        TempData["Message"] = "Success: Add Successfully";
                        return RedirectToAction(nameof(Index), new {topicId = ideaVm.TopicId});
                    }
                    var idea = _db.Ideas.Find(ideaVm.Id);
                    idea.Text = ideaVm.Text;
                    idea.DateTime = ideaVm.DateTime;
                    idea.CategoryId = ideaVm.CategoryId;
                    idea.TopicId = ideaVm.TopicId;
                    idea.UserId = claims.Value;
                

                    if (ideaVm.File != null && ideaVm.File.Length != 0)
                    {
                        var fileModel = new File
                        {
                            Name = ideaVm.File.FileName,
                            ContentType = ideaVm.File.ContentType
                        };

                        using (var memoryStream = new MemoryStream())
                        {
                            await ideaVm.File.CopyToAsync(memoryStream);
                            fileModel.Data = memoryStream.ToArray();
                        }
                        // save file new
                        _db.Files.Add(fileModel);
                        // Delete old file
                        var oldFile = _db.Files.Find(idea.FileId);
                        _db.Remove(oldFile);
                        _db.SaveChanges();
                        idea.FileId = fileModel.Id;
                    }
                
                    _db.Update(idea);
                    _db.SaveChanges();
                    return RedirectToAction(nameof(Index), new {topicId = ideaVm.TopicId});
                }
                else
                {
                    ViewData["Message"] = "Fail: You must agree Terms and Conditions before submit";
                }
            }

            ideaVm.CategoryList = categoriesSelectListItems();
            return View(ideaVm);
        }

        public IActionResult Delete(int? id)
        {
            var ideaWantToDelete = _db.Ideas.Find(id);
            _db.Ideas.Remove(ideaWantToDelete);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index), new {topicId = ideaWantToDelete.TopicId});
        }
        
        [NonAction]
        private IEnumerable<SelectListItem> categoriesSelectListItems()
        {
            var categories = _db.Categories.ToList();
            var result = categories.Select(i => new SelectListItem()
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });
            return result;
        }

        public async Task<IActionResult> Download(int id)
        {
            var fileModel = await _db.Files.FindAsync(id);
            if (fileModel == null)
                return NotFound();

            return File(fileModel.Data, fileModel.ContentType, fileModel.Name);
        }
        
        public async Task<IActionResult> Preview(int id)

EnterpriseProject/Areas/Authenticated/Controllers/ReactController.cs
using System;
using System.Linq;
using System.Security.Claims;
using EnterpriseProject.Data;
using EnterpriseProject.Models;
using EnterpriseProject.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EnterpriseProject.Areas.Authenticated.Controllers
{

    [Area(SD.Authenticated)]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Manager + "," + SD.Role_Staff + "," + SD.Role_Coordinator)]
    public class ReactController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ReactController(ApplicationDbContext db)
        {
            _db = db;
        }

        // GET

        [HttpGet]
        public IActionResult Like(int ideaId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var idea = _db.Ideas.Find(ideaId);
            var react = _db.Reacts.FirstOrDefault(i => i.UserId == claims.Value && i.IdeaId == ideaId);
            var isUserViewed = _db.Views.Any(_ => _.IdeaId == ideaId && _.UserId == claims.Value);
            if (react == null)
            {
                var newReact = new React()
                {
                    Like = 1,
                    UserId = claims.Value,
                    IdeaId = ideaId
                };
                _db.Reacts.Add(newReact);
                
                if (!isUserViewed)
                {
                    _db.Views.Add(new View()
                    {
                        VisitTime = DateTime.Now,
                        UserId = claims.Value,
                        IdeaId = ideaId
                    });
                }
                _db.SaveChanges();
                return RedirectToAction("Index", "Ideas",new {topicId = idea.TopicId});
            }
            else
            {
                if (react.DisLike == 0 && react.Like == 0)
                {
                    react.Like = 1;
                }
                else if (react.DisLike == 0)
                {
                    react.Like = 0;
                }
                else
                {
                    react.DisLike = 0;
                    react.Like = 1;
                }
            }
            _db.Reacts.Update(react);
            
            if (!isUserViewed)
            {
                _db.Views.Add(new View()
                {
                    VisitTime = DateTime.Now,
                    UserId = claims.Value,
                    IdeaId = ideaId
                });
            }
            
            _db.SaveChanges();
           
            return RedirectToAction("Index", "Ideas",new {topicId = idea.TopicId});
        }

        [HttpGet]
        public IActionResult DisLike(int ideaId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var idea = _db.Ideas.Find(ideaId);
            var react = _db.Reacts.FirstOrDefault(i => i.UserId == claims.Value && i.IdeaId == ideaId);
            var isUserViewed = _db.Views.Any(_ => _.IdeaId == ideaId && _.UserId == claims.Value);
            if (react == null)
            {
                var NewReact = new React()
                {
                    DisLike = 1,
                    UserId = claims.Value,
                    IdeaId = ideaId
                };
                _db.Reacts.Add(NewReact);
                if (!isUserViewed)
                {
                    _db.Views.Add(new View()
                    {
                        VisitTime = DateTime.Now,
                        UserId = claims.Value,
                        IdeaId = ideaId
                    });
                }
                _db.SaveChanges();
                return RedirectToAction("Index", "Ideas",new {topicId = idea.TopicId});
            }
            else
            {
                if (react.DisLike == 0 && react.Like == 0)
                {
                    react.DisLike = 1;
                }
                else if (react.Like == 0)
                {
                    react.DisLike = 0;
                }
                else
                {
                    react.Like = 0;
                    react.DisLike = 1;
                }
            }
            _db.Reacts.Update(react);
            
          
            if (!isUserViewed)
            {
                _db.Views.Add(new View()
                {
                    VisitTime = DateTime.Now,
                    UserId = claims.Value,
                    IdeaId = ideaId
                });
            }
            _db.SaveChanges();

            return RedirectToAction("Index", "Ideas",new {topicId = idea.TopicId});
        }
    }
}

EnterpriseProject/Areas/Authenticated/Views/Ideas/Index.cshtml
@using EnterpriseProject.Utility
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using System.Security.Claims
@model EnterpriseProject.ViewModels.TopicsVM

@{
    Layout = "_Layout";
    <link rel="stylesheet" href="~/css/Idead/Create.css"/>
    <link rel="stylesheet" href="~/css/Idead/BackToList.css"/>
    <link rel="stylesheet" href="~/css/Idead/Cart.css"/>
    <link rel="stylesheet" href="~/css/Idead/card-footer.css"/>
}

<div class="container">
    <div class="row">
            <div class="col-md-4">
                <h1>Idea Table</h1>
            </div>
            <div class="col-md-8">
                <div class="d-flex justify-content-end">
                    @if (Model.Topic.ClosureDate > DateTime.Now)
                    {
                        <a asp-controller="Ideas" asp-action="Upsert" asp-route-topicId="@Model.Topic.Id" class="btn btn-primary float-md-right button-create mr-1"><i class="fas fa-plus"></i> &nbsp;Create New Idea</a>
                    }
                    @* <form class="form-inline my-2 my-lg-0 float-md-right"> *@
                    @*     <input id="myInput" class="form-control mr-sm-2" type="text" placeholder="Search"> *@
                    @* </form> *@
                    <a asp-controller="Topics" asp-action="Index" class="btn btn-secondary button-back-to-list">Back To Topics Page</a>
                </div>
            </div>
        </div>
    <div class="row mt-2">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Topic Details</h5>
                    <table class="table">
                        <tbody>
                        <tr>
                            <th>Name</th>
                            <td>@Model.Topic.Name</td>
                        </tr>
                        <tr>
                            <th>Deadline 1</th>
                            <td>@Model.Topic.ClosureDate</td>
                        </tr>
                        <tr>
                            <th>Deadline 2</th>
                            <td>@Model.Topic.FinalClosureDate</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @foreach (var obj in @Model.ReactVms)
    {
        <div class="card">
            <div class="card-header">
                <ul class="list-inline card-meta">
                    <li class="list-inline-item ">
                        <i style="color: #008080;" class="fa-solid fa-user"></i>
                        User: @(User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Manager) ? obj.Idea.ApplicationUser.FullName : "anonymous")
                    </li>
                    <li class="list-inline-item">
                        <i style="color: #b30000;" class="fa-solid fa-calendar "></i>
                        Date: @obj.Idea.DateTime
                    </li>
                    <li class="list-inline-item">
                        <i style="color: #f57d00" class="fa-solid fa-tag"></i>
                        Category: @obj.Idea.Category.Name
                    </li>
                    <li class="list-inline-item">
                        <i style="color: #FCE22A" class="fa-solid fa-folder"></i>
                        Topic: @obj.Idea.Topic.Name
                    </li>
                    <li class="list-inline-item">
                        <i style="color: #0066ff;" class="fa-solid fa-thumbs-up"></i>
                        Likes: @obj.Like
                    </li>
                    <li class="list-inline-item">
                        <i style="color: #0066ff;" class="fa-solid fa-thumbs-down"></i>
                        Dislikes: @obj.DisLike
                    </li>
                    <li class="list-inline-item">
                        <i style="color: #30E3DF;" class="fa-solid fa-eye"></i>
                        Views: @obj.View
                    </li>
                    <li class="list-inline-item">
                        <i style="color: #D61355;" class="fa-solid fa-file-arrow-down"></i>
                        FileName: @obj.FileName
                    </li>
                </ul>
                <h5 class="card-title">Theme Name of ideas: @obj.Idea.Text</h5>
            </div>
            <iframe src="@Url.Action("Preview", "Ideas", new { id = obj.Idea.FileId })" width="100%" height="600"></iframe>
            <div class="card-footer mt-0">
                <div class="react-buttons">
                    @if (obj.Idea.Topic.FinalClosureDate > DateTime.Now)
                    {
                        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Manager) || User.IsInRole(SD.Role_Staff) || User.IsInRole(SD.Role_Coordinator))

                        {
                            <a asp-controller="React" asp-action="Like" asp-route-ideaId="@obj.Idea.Id" class="btn btn-outline-primary btn-sm">
                                <i class="fa-regular fa-thumbs-up"></i>
                                <span>Like</span>
                            </a>
                            <a asp-controller="React" asp-action="DisLike" asp-route-ideaId="@obj.Idea.Id" class="btn btn-outline-primary btn-sm">
                                <i class="fa-sharp fa-regular fa-thumbs-down"></i>
                                <span>Dislike</span>
                            </a>
                            <a asp-controller="Comments" asp-action="Index" asp-route-ideaId="@obj.Idea.Id" class="btn btn-outline-secondary btn-sm">
                                <i class="fa-regular fa-comments"></i>
                                <span>Comments</span>
                            </a>
                            <a asp-controller="Ideas" asp-action="Download" asp-route-id="@obj.Idea.FileId" class="btn btn-outline-dark btn-sm">
                                <i class="fa-solid fa-file-arrow-down"></i>
                                <span>Download</span>
                            </a>
                        }
                    }
                    
                    @if(User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Manager))
                    {
                        <a asp-controller="Ideas" asp-action="Upsert" asp-route-id="@obj.Idea.Id" asp-route-topicId="@Model.Topic.Id" class="btn btn-outline-warning btn-sm">
                            <i class="fa-solid fa-pen-to-square"></i>
                            <span>Edit</span>
                        </a>
                        <a asp-controller="Ideas" asp-action="Delete" asp-route-id="@obj.Idea.Id" onclick="return confirm('Do you want to delete')" class="btn btn-outline-danger btn-sm">
                            <i class="fa-solid fa-trash-can"></i>
                            <span>Delete</span>
                        </a>
                    }

                    @{
                        var claimsIdentity = (ClaimsIdentity)User.Identity;
                        var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                    }
                    @if (obj.Idea.UserId == claims.Value)
                    {
                        @if (obj.Idea.Topic.ClosureDate > DateTime.Now && obj.Idea.Topic.FinalClosureDate > DateTime.Now)
                        {
                            @if (User.IsInRole(SD.Role_Staff) || User.IsInRole(SD.Role_Coordinator))
                            {
                                <a asp-controller="Ideas" asp-action="Upsert" asp-route-id="@obj.Idea.Id" asp-route-topicId="@Model.Topic.Id" class="btn btn-outline-warning btn-sm">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                    <span>Edit</span>
                                </a>
                                <a asp-controller="Ideas" asp-action="Delete" asp-route-id="@obj.Idea.Id" onclick="return confirm('Do you want to delete')" class="btn btn-outline-danger btn-sm">
                                    <i class="fa-solid fa-trash-can"></i>
                                    <span>Delete</span>
                                </a>
                            }
                        }
                    }
                </div>
            </div>
        </div>
    }
</div>
        

@section Scripts
{
    <script>
         $(document).ready(function (){
             $("#myInput").on("keyup", function(){
              var value = $(this).val().toLowerCase();
             $("#tblData").filter(function (){
                 $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
             });
         });
     });
    </script>
}

EnterpriseProject/Areas/Authenticated/Views/Ideas/UpSert.cshtml
@model EnterpriseProject.ViewModels.IdeaVM

@{
    Layout = "_Layout";
    var title = @Model.Id != 0 ? "Update Idea" : "Create Idea";
}

<h1>@title</h1>
<partial name="_StatusMessage" model="@ViewData["Message"]"></partial>
<form method="post" enctype="multipart/form-data">
    <input asp-for="Id" class="form-control" hidden>
    <div class="mb-3">
        <label asp-for="Text" class="form-label"></label>
        <input asp-for="Text" class="form-control">
        <span asp-validation-for="Text" class="text-danger"></span>
    </div>
    <div class="mb-3">
        @if (@Model.Id != 0)
        {
            <label class="form-label" hidden="hidden">File</label>
            <p>Old File Name: @Model.FileName</p>
        }
        else
        {
            <label class="form-label">File</label>
        }
        <input type="file" name="File" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="DateTime" class="form-label"></label>
        <input asp-for="DateTime" class="form-control">
        <span asp-validation-for="DateTime" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="CategoryId" class="form-label"></label>
        @Html.DropDownListFor(m => m.CategoryId, Model.CategoryList, "Please select category", new { @class = "form-control" })
        <span asp-validation-for="CategoryId" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <input asp-for="TopicId" class="form-control" hidden>
    </div>
    <div class="form-group">
        <div class="form-check">
            <input asp-for="IsAgree" class="form-check-input" type="checkbox">
            <label asp-for="IsAgree" class="form-check-label">
                I agree with Terms and Contions
            </label>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>