EnterpriseProject/Areas/Authenticated/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using EnterpriseProject.Data;
using EnterpriseProject.Models;
using EnterpriseProject.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EnterpriseProject.Areas.Authenticated.Controllers
{
    [Area(SD.Authenticated)]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Manager)]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoriesController(ApplicationDbContext db)
        {
            _db = db;
        }
        // GET
        public IActionResult Index(string searchString)
        {
            IEnumerable<Category> listCategories = _db.Categories.ToList();
            if (!String.IsNullOrEmpty(searchString))
            {
                listCategories = listCategories.Where(c => c.Name.Contains(searchString));
            }
            return View(listCategories);
        }
        
        [HttpGet]
        public IActionResult UpSert(int? id)
        {
            if (id == null)
            {
                return View(new Category());
            }

            var findCategory = _db.Categories.Find(id);
            return View(findCategory);
        }

        [HttpPost]
        public IActionResult UpSert(Category category)
        {
            if (ModelState.IsValid)
            {
                if (category.Id == 0)
                {
                    _db.Categories.Add(category);
                    _db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }

                _db.Categories.Update(category);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        public IActionResult Delete( int id)
        {
            var deleteCategories = _db.Categories.Find(id);
            _db.Remove(deleteCategories);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

EnterpriseProject/Areas/Authenticated/Controllers/DepartmentController.cs
using System;
using System.Linq;
using EnterpriseProject.Data;
using EnterpriseProject.Models;
using EnterpriseProject.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EnterpriseProject.Areas.Authenticated.Controllers
{
    [Area(SD.Authenticated)]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Manager)]
    public class DepartmentController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DepartmentController(ApplicationDbContext db)
        {
            _db = db;
        }
        // GET
        public IActionResult Index(string searchString)
        {
            var listDeparment = _db.Departments.ToList();
            if (!String.IsNullOrEmpty(searchString))
            {
                listDeparment = listDeparment.Where(s => s.Name.Contains(searchString)).ToList();
            }
            return View(listDeparment);
        }

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            if (id == null)
            {
                return View(new Department());
            }

            var findDeparment = _db.Departments.Find(id);
            return View(findDeparment);
        }

        [HttpPost]
        public IActionResult Upsert(Department department)
        {
            if (ModelState.IsValid)
            {
                if (department.Id == 0)
                {
                    _db.Departments.Add(department);
                    _db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }

                _db.Departments.Update(department);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View(department);
        }

        public IActionResult Delete(int id)
        {
            var deleteId = _db.Departments.Find(id);
            _db.Departments.Remove(deleteId);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

EnterpriseProject/Areas/Authenticated/Controllers/StatisticsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EnterpriseProject.Data;
using EnterpriseProject.Utility;
using EnterpriseProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EnterpriseProject.Areas.Authenticated.Controllers
{
    [Area(SD.Authenticated)]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Manager)]
    public class StatisticsController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;

        public StatisticsController(ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }
        // GET
        public async Task<IActionResult> Index()
        {
            // idea by department
            var ideas = _db.Ideas.ToList();
            var userIds = ideas.Select(_ => _.UserId);
            var users = _db.ApplicationUsers.Where(_ => userIds.Contains(_.Id)).ToList();
            var departmentIds = users.Select(_ => _.DepartmentId).ToList();
            var departments = _db.Departments.Where(_ => departmentIds.Contains(_.Id)).ToList();

            var statistics = new List<Statistic>();
            foreach (var department in departments)
            {
                var usersInDepartments = users.Where(_ => _.DepartmentId == department.Id).ToList();
                var userIdsInDepartments = usersInDepartments.Select(_ => _.Id).ToList();
                var numberOfIdeas = ideas.Count(_ => userIdsInDepartments.Contains(_.UserId));
                var statistic = new Statistic()
                {
                    DepartmentName = department.Name,
                    NumberOfIdeas = numberOfIdeas
                };
                
                statistics.Add(statistic);
            }

            var departmentNoIdeas = _db.Departments.Where(_ => !departmentIds.Contains(_.Id));
            if (departmentNoIdeas.Any())
            {
                foreach (var department in departmentNoIdeas)
                {
                    var statistic = new Statistic()
                    {
                        DepartmentName = department.Name,
                        NumberOfIdeas = 0
                    };
                
                    statistics.Add(statistic);
                }
            }
            
            ViewBag.Data = statistics.Select(_=>_.NumberOfIdeas).ToArray();
            ViewBag.Labels = statistics.Select(_=>_.DepartmentName).ToArray();
            
            // percentage idea by department
            
            // number of staff by department
            var allUsers = _db.ApplicationUsers.ToList();
            foreach (var user in allUsers)
            {
                var roleTemp = await _userManager.GetRolesAsync(user);
                user.Role = roleTemp.FirstOrDefault();
            }

            var staffs = allUsers.Where(_ => _.Role == SD.Role_Staff).ToList();
            var departmentAll = _db.Departments.ToList();

            var statisticUsers = new List<Statistic>();
            foreach (var department in departmentAll)
            {
                var statistic = new Statistic()
                {
                    DepartmentName = department.Name,
                    NumberOfIdeas = staffs.Count(_ => _.DepartmentId == department.Id)
                };
                
                statisticUsers.Add(statistic);
            }
            
            ViewBag.DataCtv = statisticUsers.Select(_=>_.NumberOfIdeas).ToArray();
            ViewBag.LabelCtv = statisticUsers.Select(_=>_.DepartmentName).ToArray();
          
            return View();
        }
    }
}

EnterpriseProject/Areas/Authenticated/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using EnterpriseProject.Data;
using EnterpriseProject.Models;
using EnterpriseProject.Utility;
using EnterpriseProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using CompressionLevel = System.IO.Compression.CompressionLevel;
using File = EnterpriseProject.Models.File;

namespace EnterpriseProject.Areas.Authenticated.Controllers
{
    [Area(SD.Authenticated)]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Manager + "," + SD.Role_Staff + "," + SD.Role_Coordinator)]
    
    public class TopicsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public TopicsController(ApplicationDbContext db)
        {
            _db = db;
        }
        // GET
        public IActionResult Index(string searchString)
        {
            IEnumerable<Topic> listTopic = _db.Topics.ToList();
            if (!String.IsNullOrEmpty(searchString))
            {
                listTopic = listTopic.Where(c => c.Name.Contains(searchString));
            }
            return View(listTopic);
        }

        [HttpGet]
        public IActionResult UpSert(int? id)
        {
            if (id == null)
            {
                return View(new Topic());
            }

            var findTopic = _db.Topics.Find(id);
            return View(findTopic);
        }

        [HttpPost]
        public IActionResult UpSert(Topic topic)
        {
            if (ModelState.IsValid)
            {
                if (topic.Id == 0)
                {
                    _db.Topics.Add(topic);
                    _db.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }

                _db.Topics.Update(topic);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(topic);
        }

        public IActionResult Delete(int id)
        {
            var findId = _db.Topics.Find(id);
            _db.Remove(findId);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        
        public ActionResult DownloadZipFile(int topicId)
        {
            // Take all ideas related to the topic by ID of the topic
            var ideas = _db.Ideas.Where(_ => _.TopicId == topicId);

            // Take the list of all files attached to ideas
            var fileIds = ideas.Select(_ => _.FileId).ToList();
            
            // Take all the attached files from the database based on their ID list
            var zipFile = _db.Files.Where(f => fileIds.Contains(f.Id)).ToList();

            // Create a temporary folder to store files
            var tempDirectory = Path.Combine(Path.GetTempPath(), _db.Topics.Find(topicId).Id.ToString());

            // If the folder has existed, deleted it
            if (Directory.Exists(tempDirectory))
            {
                Directory.Delete(tempDirectory, true);
            }
            Directory.CreateDirectory(tempDirectory);

            // Create a new folder to store files
            foreach (var file in zipFile)
            {
                var ideaId = _db.Ideas.Where(i => i.FileId == file.Id).FirstOrDefault().Id.ToString();
                var filePath = Path.Combine(tempDirectory, ideaId);
                // If the folder has existed, deleted it
                if (Directory.Exists(filePath))
                {
                    Directory.Delete(filePath, true);
                }
                Directory.CreateDirectory(filePath);
                using (var fileStream = new FileStream(Path.Combine(filePath, file.Name), FileMode.Create))
                {
                    fileStream.Write(file.Data, 0, file.Data.Length);
                }
            }

            // Create a compressed file and add files to it
            var zipFilePath = Path.Combine(Path.GetTempPath(), _db.Topics.Find(topicId).Name + ".zip");
            if (System.IO.File.Exists(zipFilePath))
            {
                System.IO.File.Delete(zipFilePath);
            }
            
            ZipFile.CreateFromDirectory(tempDirectory, zipFilePath);

            // Set the type of content and title for feedback
            var contentType = "application/zip";
            var contentDisposition = "attachment; filename="+ _db.Topics.Find(topicId).Name+".zip";
            Response.Headers.Add("Content-Disposition", contentDisposition);

            // Download zip file
            return PhysicalFile(zipFilePath, contentType);
        }
        
        public FileResult DownloadExcel(int topicId)
        {
            var listIdea = _db.Ideas.Where(_=>_.TopicId == topicId).Include(i => i.ApplicationUser)
                .Include(i => i.Category)
                .Include(i => i.Topic).ToList();
            
            // Create a new Excel package
            using (var package = new ExcelPackage())
            {
                // Add a new worksheet to the Excel package
                var worksheet = package.Workbook.Worksheets.Add("Sheet1");

                // Define the title row
                worksheet.Cells[1, 1].Value = "No.";
                worksheet.Cells[1, 2].Value = "Text";
                worksheet.Cells[1, 3].Value = "File Name";
                worksheet.Cells[1, 4].Value = "User Name";
                worksheet.Cells[1, 5].Value = "Topic Name";
                worksheet.Cells[1, 6].Value = "Category Name";
                worksheet.Cells[1, 7].Value = "View";
                worksheet.Cells[1, 8].Value = "Like";
                worksheet.Cells[1, 9].Value = "Dislike";

                // Add some sample data rows
                int no = 1;
                int index = 2;
                foreach (var idea in listIdea)
                {
                    var like = _db.Reacts.Where(_ => _.IdeaId == idea.Id).Sum(_ => _.Like);
                    var disLike = _db.Reacts.Where(_ => _.IdeaId == idea.Id).Sum(_ => _.DisLike);
                    var view = _db.Views.Count(_ => _.IdeaId == idea.Id);
                    worksheet.Cells[index, 1].Value = no;
                    worksheet.Cells[index, 2].Value = idea.Text;
                    worksheet.Cells[index, 3].Value = _db.Files.Find(idea.FileId).Name;
                    worksheet.Cells[index, 4].Value = idea.ApplicationUser.FullName;
                    worksheet.Cells[index, 5].Value = idea.Topic.Name;
                    worksheet.Cells[index, 6].Value = idea.Category.Name;
                    worksheet.Cells[index, 7].Value = view;
                    worksheet.Cells[index, 8].Value = like;
                    worksheet.Cells[index, 9].Value = disLike;
                    no++;
                    index++;
                }
                
                // Auto-fit the columns to the content
                worksheet.Cells.AutoFitColumns();

                // Convert the Excel package to a byte array
                var fileContents = package.GetAsByteArray();

                // Set the file name and content type for the Excel file
                var fileName = _db.Topics.Find(topicId).Name +".xlsx";
                var contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                
                // Return the Excel file as a FileResult
                return File(fileContents, contentType, fileName);
            }
        }

    }
}

EnterpriseProject/Views/Shared/_Layout-home.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using EnterpriseProject.Utility
@using OfficeOpenXml.FormulaParsing.Excel.Functions.DateTime
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - EnterpriseProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
     <link rel="stylesheet" href="~/css/Home-page/footer.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body style="margin-bottom: 0">
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
        <div class="container">
            <a class="navbar-brand" asp-area="UnAuthenticated" asp-controller="Home" asp-action="Index">EnterpriseProject</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Manager))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" asp-area="UnAuthenticated" asp-controller="Home" asp-action="Index" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Home
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <ul class="list-unstyled">
                                    <li>
                                        <a class="dropdown-item" asp-area="Authenticated" asp-controller="UsersManagement" asp-action="index">UsersManagement</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Authenticated" asp-controller="Department" asp-action="index">Department</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Authenticated" asp-controller="Categories" asp-action="index">Category</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Authenticated" asp-controller="Topics" asp-action="index">Topics</a>
                                    </li>
                                </ul>
                            </div>
                             
                        </li>
                    }
                    @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Manager) || User.IsInRole(SD.Role_Staff) || User.IsInRole(SD.Role_Coordinator))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Authenticated" asp-controller="Topics" asp-action="index">Topics</a>
                        </li>
                    }
                    @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Manager))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Authenticated" asp-controller="Statistics" asp-action="index">Statistics</a>
                        </li>
                    }
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div >
    </nav>
</header>
<div>
    <main role="main">
        @RenderBody()
    </main>
</div>
<footer style="padding: 0">
    <div class="container">
    <div class="row">
        <div class="col">
            <h3>Contact us</h3>
            <p>Hotline: 086.779.1686</p>
            <p>Email: info@greenwich.edu.vn</p>
        </div>
        <div class="col">
            <h3>Ho Chi Minh Facility</h3>
            <p>Phone: 028.7300.2266</p>
            <p>Address: 20 Cong Hoa Street Tan Binh District</p>
        </div>
        <div class="col">
            <h3>Social networking sites</h3>
            <div class="social-links ">
                <a href=https://www.facebook.com/GreenwichVietnam/?utm_source=google&utm_medium=search&utm_campaign=brand_greenwich&utm_term=greenwich_vietnam><i class="fab fa-facebook"></i></a>
                <a href="https://twitter.com/UniofGreenwich"><i class="fab fa-twitter"></i></a>
                <a href="https://www.linkedin.com/school/university-of-greenwich/"><i class="fab fa-linkedin"></i></a>
                <a href="https://www.youtube.com/user/UniversityGreenwich"><i class="fab fa-youtube"></i></a>
            </div>
        </div>
    </div>
    </div>
    <div class="copy">
        <p>&copy; @DateTime.Now.Year Greenwich.edu.vn. All rights reserved.</p>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EnterpriseProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using EnterpriseProject.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - EnterpriseProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="UnAuthenticated" asp-controller="Home" asp-action="Index">EnterpriseProject</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Manager))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" asp-area="UnAuthenticated" asp-controller="Home" asp-action="Index" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Home
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <ul class="list-unstyled">
                                    <li>
                                        <a class="dropdown-item" asp-area="Authenticated" asp-controller="UsersManagement" asp-action="index">Users Management</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Authenticated" asp-controller="Department" asp-action="index">Department</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Authenticated" asp-controller="Categories" asp-action="index">Category</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Authenticated" asp-controller="Topics" asp-action="index">Topics</a>
                                    </li>
                                </ul>
                            </div>
                             
                        </li>
                    }
                    @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Manager) || User.IsInRole(SD.Role_Staff) || User.IsInRole(SD.Role_Coordinator))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Authenticated" asp-controller="Topics" asp-action="index">Topics</a>
                        </li>
                    }
                    @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Manager))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Authenticated" asp-controller="Statistics" asp-action="index">Statistics</a>
                        </li>
                    }
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div >
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
       &copy; @DateTime.Now.Year - EnterpriseProject
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EnterpriseProject/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Fail") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>    
}