EnterpriseProject/Models/Comment.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EnterpriseProject.Models
{
    public class Comment
    {
        [Key] public int Id { get; set; }
        public string Text { get; set; }
        public DateTime DateTime { get; set; }
        [Required] public int IdeaId { get; set; }
        [Required] public string UserId { get; set; }
        [ForeignKey("UserId")] public ApplicationUser ApplicationUser { get; set; }
        
    }
}

EnterpriseProject/Areas/Authenticated/Controllers/CommentsController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EnterpriseProject.Data;
using EnterpriseProject.Models;
using EnterpriseProject.Utility;
using EnterpriseProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EnterpriseProject.Areas.Authenticated.Controllers
{
    [Area(SD.Authenticated)]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Manager + "," + SD.Role_Staff + "," + SD.Role_Coordinator)]
    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly ISendMailService _emailSender;

        public CommentsController(ApplicationDbContext db, ISendMailService emailSender)
        {
            _db = db;
            _emailSender = emailSender;
        }
        // GET
        public IActionResult Index(int ideaId)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var isUserViewed = _db.Views.Any(_ => _.IdeaId == ideaId && _.UserId == claims.Value);
            if (!isUserViewed)
            {
                _db.Views.Add(new View()
                {
                    VisitTime = DateTime.Now,
                    UserId = claims.Value,
                    IdeaId = ideaId
                });
                _db.SaveChanges();
            }
            
            var listComments = _db.Comments.Where(_=>_.IdeaId == ideaId).Include(u => u.ApplicationUser).ToList();
            var view = _db.Views.Count(_ => _.IdeaId == ideaId);

            var idea = _db.Ideas.Where(_ => _.Id == ideaId).Include(_ => _.Topic).Include(_ => _.Category)
                .Include(_ => _.ApplicationUser).FirstOrDefault();

            var vm = new CommentVM()
            {
                FileName = _db.Files.Find(idea.FileId).Name,
                Comments = listComments,
                View = view,
                IdeaId = ideaId,
                Idea = idea
            };

            return View(vm);
        }
        
        [HttpGet]
        public IActionResult UpDate(int? id)
        {
            var findComment = _db.Comments.Find(id);
            return View(findComment);
        }
        
        [HttpPost]
        public IActionResult UpDate(Comment comment)
        {
            var findComment = _db.Comments.Find(comment.Id);
            findComment.Text = comment.Text;
            findComment.DateTime = DateTime.Now;
            _db.Comments.Update(findComment);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index), new {ideaId = findComment.IdeaId});
        }
        
        public IActionResult Delete(int id)
        {
            var deleteComment = _db.Comments.Find(id);
            _db.Remove(deleteComment);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index), new { ideaId = deleteComment.IdeaId});
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(CommentVM commentVm)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            
            var comment = new Comment()
            {
                IdeaId = commentVm.IdeaId,
                Text = commentVm.Text,
                DateTime = DateTime.Now,
                UserId = claims.Value
            };

            _db.Comments.Add(comment);
            _db.SaveChanges();

            var idea = _db.Ideas.FirstOrDefault(_ => _.Id == commentVm.IdeaId);
            var userOwnerIdea = _db.ApplicationUsers.Find(idea.UserId);
            if (userOwnerIdea != null && userOwnerIdea.Email != null)
            {
                await _emailSender
                    .SendEmailAsync(userOwnerIdea.Email, "New Comment for your idea",
                        $"<div style='color: black;'><h1 style='color: black;'>Have a new comment on your idea</h1><p style='color: black;'><strong>From:</strong> {_db.ApplicationUsers.Find(claims.Value).FullName} ({_db.ApplicationUsers.Find(claims.Value).Email})</p><p style='color: black;'><strong>Content new comments are:</strong> {comment.Text}</p><p style='color: black;'><strong>Further Comments in the Idea:</strong> {_db.Ideas.Find(idea.Id).Text}</p><p style='color: black;'><strong>Time for posting Comment:</strong> {_db.Ideas.Find(idea.Id).DateTime}</p><p style='color: black;'><strong>Best Regards!</strong></p></div></div>");
            }
            return RedirectToAction(nameof(Index), new {ideaId = commentVm.IdeaId});
        }
    }
}

EnterpriseProject/Areas/Authenticated/Controllers/IdeasController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EnterpriseProject.Data;
using EnterpriseProject.Models;
using EnterpriseProject.Utility;
using EnterpriseProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using File = EnterpriseProject.Models.File;

namespace EnterpriseProject.Areas.Authenticated.Controllers
{
    [Area(SD.Authenticated)]
    [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Manager + "," + SD.Role_Staff + "," + SD.Role_Coordinator)]
    public class IdeasController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ISendMailService _emailSender;

        public IdeasController(ApplicationDbContext db,UserManager<IdentityUser> userManager, ISendMailService emailSender)
        {
            _db = db;
            _userManager = userManager;
            _emailSender = emailSender;
        }
        // GET
        public IActionResult Index(string searchString, int topicId)
        {
            ViewData["Message"] = TempData["Message"];
            var listIdea = _db.Ideas.Where(_=>_.TopicId == topicId).Include(i => i.ApplicationUser)
                .Include(i => i.Category)
                .Include(i => i.Topic).ToList();
            
            var reacts = new List<ReactVM>();
            
            if (!String.IsNullOrEmpty(searchString))
            {
                listIdea = listIdea.Where(s => s.Text.Contains(searchString)).ToList();
            }
            
            foreach (var idea in listIdea)
            {
                var like = _db.Reacts.Where(_ => _.IdeaId == idea.Id).Sum(_ => _.Like);
                var disLike = _db.Reacts.Where(_ => _.IdeaId == idea.Id).Sum(_ => _.DisLike);
                var view = _db.Views.Count(_ => _.IdeaId == idea.Id);
                var fileName = _db.Files.FirstOrDefault(_ => _.Id == idea.FileId).Name;
                var react = new ReactVM()
                {
                    View = view,
                    Idea = idea,
                    Like = like,
                    DisLike = disLike,
                    FileName = fileName
                };
                
                reacts.Add(react);
            }

            var response = new TopicsVM()
            {
                ReactVms = reacts,
                Topic = _db.Topics.Find(topicId)
            };
            
            return View(response);
        }

        [HttpGet]
        public IActionResult Upsert(int? id, int topicId )
        {
            
            IdeaVM ideaVm = new IdeaVM()
            {
                CategoryList = categoriesSelectListItems(),
                TopicId = topicId
            };
            
            if (id == null)
            {
                return View(ideaVm);
            }

            var idea = _db.Ideas.Find(id);
            ideaVm.Id = idea.Id;
            ideaVm.Text = idea.Text;
            ideaVm.DateTime = idea.DateTime;
            ideaVm.CategoryId = idea.CategoryId;
            ideaVm.TopicId = idea.TopicId;
            ideaVm.FileName = _db.Files.Find(idea.FileId).Name;
            return View(ideaVm);
        }
        
        
        [HttpPost]
        public async Task<IActionResult> UpSert(IdeaVM ideaVm)
        {
            if (ModelState.IsValid)
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                
                if (ideaVm.IsAgree)
                {
                    if (ideaVm.Id == 0)
                    {
                        // SendEmail to QA coordinator
                        var currentUser = _db.ApplicationUsers.FirstOrDefault(i => i.Id == claims.Value);
                        var userList = _db.ApplicationUsers.Where(_ => _.DepartmentId == currentUser.DepartmentId).ToList();
                        ApplicationUser qaCoordinator = new ApplicationUser();
                        foreach (var user in userList)
                        {
                            var roleTemp = await _userManager.GetRolesAsync(user);
                            if (roleTemp.First() == SD.Role_Coordinator)
                            {
                                qaCoordinator = user;
                                break;
                            }
                        }
                        
                        // add file
                        if (ideaVm.File == null || ideaVm.File.Length == 0)
                            return BadRequest("No file selected");

                        var fileModel = new File
                        {
                            Name = ideaVm.File.FileName,
                            ContentType = ideaVm.File.ContentType
                        };

                        using (var memoryStream = new MemoryStream())
                        {
                            await ideaVm.File.CopyToAsync(memoryStream);
                            fileModel.Data = memoryStream.ToArray();
                        }
                        _db.Files.Add(fileModel);
                        _db.SaveChanges();
                        
                        // create idea
                        var ideaCreate = new Idea()
                        {
                            Text = ideaVm.Text,
                            DateTime = ideaVm.DateTime,
                            FileId = fileModel.Id,
                            CategoryId = ideaVm.CategoryId,
                            TopicId = ideaVm.TopicId,
                            UserId = claims.Value
                        };
                        _db.Ideas.Add(ideaCreate);
                        _db.SaveChanges();

                        // Check idea is successful or not and send mail to coordinator
                        if (qaCoordinator != null && qaCoordinator.Email != null)
                        {
                            await _emailSender.SendEmailAsync(qaCoordinator.Email, "New Idea Is Added",
                                $"<div style='color: black;'><h1 style='color: black;'>New Idea Is Added</h1><p style='color: black;'><strong>From:</strong> {_db.ApplicationUsers.Find(claims.Value).FullName} ({_db.ApplicationUsers.Find(claims.Value).Email})</p><p style='color: black;'><strong>The new idea's name is added by:</strong> {_db.Ideas.Find(ideaCreate.Id).Text}</p><p style='color: black;'><strong>ideas added in topics:</strong> {_db.Topics.Find(ideaVm.TopicId).Name}</p><p style='color: black;'><strong>Time for posting ideas:</strong> {_db.Ideas.Find(ideaCreate.Id).DateTime}</p><p style='color: black;'><strong>Best Regards!</strong></p></div>");
                        }
                        TempData["Message"] = "Success: Add Successfully";
                        return RedirectToAction(nameof(Index), new {topicId = ideaVm.TopicId});
                    }
                    var idea = _db.Ideas.Find(ideaVm.Id);
                    idea.Text = ideaVm.Text;
                    idea.DateTime = ideaVm.DateTime;
                    idea.CategoryId = ideaVm.CategoryId;
                    idea.TopicId = ideaVm.TopicId;
                    idea.UserId = claims.Value;
                

                    if (ideaVm.File != null && ideaVm.File.Length != 0)
                    {
                        var fileModel = new File
                        {
                            Name = ideaVm.File.FileName,
                            ContentType = ideaVm.File.ContentType
                        };

                        using (var memoryStream = new MemoryStream())
                        {
                            await ideaVm.File.CopyToAsync(memoryStream);
                            fileModel.Data = memoryStream.ToArray();
                        }
                        // save file new
                        _db.Files.Add(fileModel);
                        // Delete old file
                        var oldFile = _db.Files.Find(idea.FileId);
                        _db.Remove(oldFile);
                        _db.SaveChanges();
                        idea.FileId = fileModel.Id;
                    }
                
                    _db.Update(idea);
                    _db.SaveChanges();
                    return RedirectToAction(nameof(Index), new {topicId = ideaVm.TopicId});
                }
                else
                {
                    ViewData["Message"] = "Fail: You must agree Terms and Conditions before submit";
                }
            }

            ideaVm.CategoryList = categoriesSelectListItems();
            return View(ideaVm);
        }

        public IActionResult Delete(int? id)
        {
            var ideaWantToDelete = _db.Ideas.Find(id);
            _db.Ideas.Remove(ideaWantToDelete);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index), new {topicId = ideaWantToDelete.TopicId});
        }
        
        [NonAction]
        private IEnumerable<SelectListItem> categoriesSelectListItems()
        {
            var categories = _db.Categories.ToList();
            var result = categories.Select(i => new SelectListItem()
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });
            return result;
        }

        public async Task<IActionResult> Download(int id)
        {
            var fileModel = await _db.Files.FindAsync(id);
            if (fileModel == null)
                return NotFound();

            return File(fileModel.Data, fileModel.ContentType, fileModel.Name);
        }
        
        public async Task<IActionResult> Preview(int id)

EnterpriseProject/Areas/Authenticated/Views/Comments/Index.cshtml
@using EnterpriseProject.Utility
@using System.Security.Claims
@model EnterpriseProject.ViewModels.CommentVM

@{
    Layout = "_Layout";
    <link rel="stylesheet" href="~/css/Comments/Create.css"/>
    <link rel="stylesheet" href="~/css/Comments/BackToList.css"/>
    <link rel="stylesheet" href="~/css/Comments/Comments.css"/>
}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Comments Table</h1>
        </div>
    </div>
        </div>
        <div class="card">
            <div class="card-header">
                <ul class="list-inline card-meta">
                    <li class="list-inline-item ">
                        <i style="color: #008080;" class="fa-solid fa-user"></i>
                        User: @(User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Manager) ? Model.Idea.ApplicationUser.FullName : "anonymous")
                    </li>
                    <li class="list-inline-item">
                        <i style="color: #F94A29;" class="fa-solid fa-tag"></i>
                        Category: @Model.Idea.Category.Name
                    </li>
                    <li class="list-inline-item">
                        <i style="color: #FCE22A;" class="fa-solid fa-folder"></i>
                        Topic: @Model.Idea.Topic.Name
                    </li>
                    <li class="list-inline-item">
                        <i style="color: #D61355;" class="fa-solid fa-file-arrow-down"></i>
                        FileName: @Model.FileName
                    </li>
                    <li class="list-inline-item">
                        <i style="color: #30E3DF;" class="fa-solid fa-eye"></i>
                        Views: @Model.View
                    </li>
                </ul>
                <h5 class="card-title">Theme Name of ideas: @Model.Idea.Text</h5>
            </div>
        </div>
    <iframe src="@Url.Action("Preview", "Ideas", new { id = Model.Idea.FileId })" width="100%" height="600"></iframe>
    <form method="post" asp-action="AddComment">
        <input asp-for="IdeaId" class="form-control" hidden>
        <div class="d-flex">
            <input asp-for="Text" class="form-control" style="margin: 0 auto" placeholder="Enter your comment">
            <button type="submit" class="btn button-create col-2" style="margin: 0 auto; margin-left: 2px; "><i class="fa fa-paper-plane"></i> Comment</button>
        </div>
    </form>
    <br/>
<div class="comments">
    @foreach (var obj in @Model.Comments)
    {
        <div class="comment" id="tblData tr">
            <div class="comment-header">
                <span class="comment-user">
                    @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Manager))
                    {
                        @obj.ApplicationUser.FullName
                    }
                    else
                    {
                        <TempData>anonymous</TempData>
                    }
                </span>
                <span class="comment-datetime">@obj.DateTime</span>
            </div>
            <div class="comment-body">
                <div class="comment-text">@obj.Text</div>
                <div class="comment-actions">
                    @{
                        var claimsIdentity = (ClaimsIdentity)User.Identity;
                        var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                    }
                    @if (obj.UserId == claims.Value)
                    {
                        //edit comments
                        @if (User.IsInRole(SD.Role_Staff) || User.IsInRole(SD.Role_Coordinator) || User.IsInRole(SD.Role_Manager) || User.IsInRole(SD.Role_Admin))
                        {
                            <a class="comment-action edit" asp-controller="Comments" asp-action="UpDate" asp-route-id="@obj.Id"><i class="fa-solid fa-pen-to-square"></i> Update</a>
                            <a class="comment-action delete" asp-controller="Comments" asp-action="Delete" onclick="return confirm('Do you want to delete')" asp-route-id="@obj.Id"><i class="fa-solid fa-trash-can"></i> Delete</a>
                        }
                    }else if(User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Manager))
                    {
                        //delete
                        <a class="comment-action delete" asp-controller="Comments" asp-action="Delete" onclick="return confirm('Do you want to delete')" asp-route-id="@obj.Id"><i class="fa-solid fa-trash-can"></i> Delete</a>
                    }
                </div>
            </div>
        </div>
    }
</div>

EnterpriseProject/Areas/Authenticated/Views/Comments/UpDate.cshtml
@model EnterpriseProject.Models.Comment

@{
    Layout = "_Layout";
}

<h1>Update Comment</h1>
<form method="post">
    <input asp-for="Id" class="form-control" hidden>
    <div class="mb-3">
        <label asp-for="Text" class="form-label"></label>
        <input asp-for="Text" class="form-control">
        <span asp-validation-for="Text" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>